
const shift = [
    {
      "id": "3388164",
      "name": "A",
      "start_time": "06:00",
      "end_time": "14:00",
      "cross": 0,
      "type": "1",
      "rest_start_time": "",
      "rest_end_time": "",
      "rest_work_hours": 0,
      "rest_work_minute": 0,
      "work_hours": "8.00h",
      "schedule_type": 0,
      "schedule_id": "3388164",
      "schedule_name": "A"
    },
    {
      "id": "3388165",
      "name": "B",
      "start_time": "06:30",
      "end_time": "14:30",
      "cross": 0,
      "type": "1",
      "rest_start_time": "",
      "rest_end_time": "",
      "rest_work_hours": 0,
      "rest_work_minute": 0,
      "work_hours": "8.00h",
      "schedule_type": 0,
      "schedule_id": "3388165",
      "schedule_name": "B"
    },
    {
      "id": "3388166",
      "name": "C",
      "start_time": "07:00",
      "end_time": "15:00",
      "cross": 0,
      "type": "1",
      "rest_start_time": "",
      "rest_end_time": "",
      "rest_work_hours": 0,
      "rest_work_minute": 0,
      "work_hours": "8.00h",
      "schedule_type": 0,
      "schedule_id": "3388166",
      "schedule_name": "C"
    },
    {
      "id": "3388167",
      "name": "D",
      "start_time": "07:30",
      "end_time": "15:30",
      "cross": 0,
      "type": "1",
      "rest_start_time": "",
      "rest_end_time": "",
      "rest_work_hours": 0,
      "rest_work_minute": 0,
      "work_hours": "8.00h",
      "schedule_type": 0,
      "schedule_id": "3388167",
      "schedule_name": "D"
    },
    {
      "id": "3388168",
      "name": "E",
      "start_time": "08:00",
      "end_time": "16:00",
      "cross": 0,
      "type": "1",
      "rest_start_time": "",
      "rest_end_time": "",
      "rest_work_hours": 0,
      "rest_work_minute": 0,
      "work_hours": "8.00h",
      "schedule_type": 0,
      "schedule_id": "3388168",
      "schedule_name": "E"
    },
    {
      "id": "3388169",
      "name": "F",
      "start_time": "09:00",
      "end_time": "17:00",
      "cross": 0,
      "type": "1",
      "rest_start_time": "",
      "rest_end_time": "",
      "rest_work_hours": 0,
      "rest_work_minute": 0,
      "work_hours": "8.00h",
      "schedule_type": 0,
      "schedule_id": "3388169",
      "schedule_name": "F"
    },
    {
      "id": "3388170",
      "name": "G",
      "start_time": "09:30",
      "end_time": "15:00",
      "cross": 0,
      "type": "1",
      "rest_start_time": "",
      "rest_end_time": "",
      "rest_work_hours": 0,
      "rest_work_minute": 0,
      "work_hours": "5.50h",
      "schedule_type": 0,
      "schedule_id": "3388170",
      "schedule_name": "G"
    },
    {
      "id": "3388171",
      "name": "H",
      "start_time": "10:00",
      "end_time": "18:00",
      "cross": 0,
      "type": "1",
      "rest_start_time": "",
      "rest_end_time": "",
      "rest_work_hours": 0,
      "rest_work_minute": 0,
      "work_hours": "8.00h",
      "schedule_type": 0,
      "schedule_id": "3388171",
      "schedule_name": "H"
    },
  ] 

  export  {
    shift,
  };